const { runAgentPrompt } = require('../services/geminiService');
const IncidentDetectionAgent = require('./IncidentDetectionAgent');
const RiskAssessmentAgent = require('./RiskAssessmentAgent');
const IntelligenceAgent = require('./IntelligenceAgent');
const WeatherAgent = require('./WeatherAgent');
const MissionPlannerAgent = require('./MissionPlannerAgent');
const RoutePlanningAgent = require('./RoutePlanningAgent');
const ResourceAllocationAgent = require('./ResourceAllocationAgent');
const HospitalAvailabilityAgent = require('./HospitalAvailabilityAgent');
const CitizenCommunicationAgent = require('./CitizenCommunicationAgent');
const SituationReportAgent = require('./SituationReportAgent');
const db = require('../database/db');
const { randomUUID } = require('crypto');

const SYSTEM_PROMPT = `You are the Commander Agent, the Master Orchestrator of RESQ Emergency Operations Center.
You coordinate autonomous specialized AI agents:
Detection, Risk Assessment, Intelligence, Weather, Mission Planner, Route Planning, Resource Allocation, Hospital Availability, Citizen Communication, Situation Report.

Your duties:
1. Coordinate all agents in sequence and parallel.
2. Prioritize life-saving interventions above all.
3. Resolve resource or routing conflicts.
4. Trigger continuous replanning when environmental inputs degrade.
5. Explain every decision transparently.

Respond strictly in JSON matching the Commander schema:
{
  "summary": "",
  "reasoning": "",
  "confidence": 96,
  "recommendations": [],
  "nextAction": "",
  "priority": "Critical",
  "overallPlan": "",
  "assignedAgents": [],
  "conflictsResolved": [],
  "replanRequired": false,
  "estimatedCompletion": ""
}`;

/**
 * Executes a full multi-agent orchestration cycle for a given incident.
 */
async function orchestrate(incidentData, triggerSource = 'Initial Incident Report') {
  console.log(`[Commander Agent] Starting multi-agent cycle for incident ID: ${incidentData.id || 'NEW'} (Trigger: ${triggerSource})`);

  // Fetch contextual database state
  const availableResources = db.prepare("SELECT * FROM resources WHERE status = 'Available'").all();
  const hospitalData = db.prepare("SELECT * FROM hospitals").all();
  const hazardReports = db.prepare("SELECT * FROM hazard_reports").all();

  // Run sub-agents concurrently / sequentially
  const detectionResult = await IncidentDetectionAgent.process(incidentData);
  const riskResult = await RiskAssessmentAgent.process(incidentData);
  const intelResult = await IntelligenceAgent.process(incidentData);
  const weatherResult = await WeatherAgent.process(incidentData);
  const missionResult = await MissionPlannerAgent.process(incidentData);
  const resourceResult = await ResourceAllocationAgent.process(incidentData, availableResources);
  const routeResult = await RoutePlanningAgent.process(incidentData, hazardReports);
  const hospitalResult = await HospitalAvailabilityAgent.process(incidentData, hospitalData);
  const citizenResult = await CitizenCommunicationAgent.process(incidentData);

  // Combine sub-agent intelligence into Commander prompt payload
  const combinedContext = {
    triggerSource,
    incident: incidentData,
    agentOutputs: {
      Detection: detectionResult,
      RiskAssessment: riskResult,
      Intelligence: intelResult,
      Weather: weatherResult,
      MissionPlanner: missionResult,
      ResourceAllocation: resourceResult,
      RoutePlanning: routeResult,
      HospitalAvailability: hospitalResult,
      CitizenCommunication: citizenResult,
    }
  };

  const commanderDecision = await runAgentPrompt('Commander Agent', SYSTEM_PROMPT, combinedContext, true);

  // Save AI Decision into Database for Audit & Transparency Log
  const decisionId = randomUUID();
  try {
    const stmt = db.prepare(`
      INSERT INTO ai_decisions (
        id, agent_name, incident_id, summary, reasoning, confidence, recommendations,
        next_action, priority, overall_plan, assigned_agents, conflicts_resolved, replan_required, estimated_completion
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    stmt.run(
      decisionId,
      'Commander Agent',
      incidentData.id || null,
      commanderDecision.summary,
      commanderDecision.reasoning,
      commanderDecision.confidence,
      JSON.stringify(commanderDecision.recommendations),
      commanderDecision.nextAction,
      commanderDecision.priority,
      commanderDecision.overallPlan,
      JSON.stringify(commanderDecision.assignedAgents),
      JSON.stringify(commanderDecision.conflictsResolved),
      commanderDecision.replanRequired ? 1 : 0,
      commanderDecision.estimatedCompletion
    );

    // Save notification generated by Citizen Communication Agent
    if (citizenResult && citizenResult.summary) {
      const notifId = randomUUID();
      db.prepare(`
        INSERT INTO notifications (id, incident_id, recipient_role, message, language, type)
        VALUES (?, ?, 'all', ?, 'en', ?)
      `).run(notifId, incidentData.id || null, citizenResult.summary, commanderDecision.priority === 'Critical' ? 'Evacuation' : 'Warning');
    }
  } catch (err) {
    console.error('Failed to log AI decision to DB:', err);
  }

  return {
    commanderDecision,
    subAgents: {
      Detection: detectionResult,
      RiskAssessment: riskResult,
      Intelligence: intelResult,
      Weather: weatherResult,
      MissionPlanner: missionResult,
      ResourceAllocation: resourceResult,
      RoutePlanning: routeResult,
      HospitalAvailability: hospitalResult,
      CitizenCommunication: citizenResult,
    }
  };
}

module.exports = { orchestrate };
